config/routes.rb
Rails.application.routes.draw do

  root 'ideas#index'
  
  resources :ideas
  
  get 'about' => 'static_pages#about'
  get 'random' => 'static_pages#random'

end

app/models/idea.rb
#Creating Idea Model
class Idea < ActiveRecord::Base
    #Form validation for Ideas
    validates :description, :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
    #Main method to be called when user browses the home page
    def index
        #@ideas = Idea.all.paginate(:page => params[:page], :per_page => 5)
        @ideas = Idea.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
    end
    
    #Method to create new Idea
    def create
        @idea = Idea.create(idea_params)
        if @idea.valid?
            #
        else
            flash[:alert] = "Invalid Idea. Please try again!"
        end
        
        redirect_to root_path
    end
    #end Idea create method
    
    #Method to edit ideas
    def edit
        @idea = Idea.find(params[:id])
    end
    #end Idea edit method
    
    #Method to update ideas
    def update
        @idea = Idea.find(params[:id])
        if @idea.update(idea_params)
            redirect_to root_path
        else
            redirect_to edit_idea_path(params[:id])
        end
    end
    #end Idea update method
    
    #Method to delete ideas
    def destroy
        @idea = Idea.find(params[:id])
        @idea.destroy
        redirect_to root_path
    end
    #end Idea delete method
    
    #This method prevents users from passing malicious code to the server
    private
    
    def idea_params
        params.require(:idea).permit(:description, :author)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def about
        
    end
    
    def random
        @idea = Idea.order("RANDOM()").first
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ideas/edit.html.erb
<!-- Template to edit ideas -->
<section class="ideator__block ideator__block--editForm">
    <div class="ideator__block-row">
        
        <div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <header class="ideator__block--header ideator__block--title">
                        <h1>Revise Idea</h1>
                    </header>
                    <%= simple_form_for @idea, method: :patch do | f | %>
                        <%= f.input :description %>
                        <%= f.input :author %>
                        <%= f.submit 'Submit', class: 'btn btn-primary' %>
                    <% end %>
                </div>
            </div>
        </div>
        
    </div>
</section><!-- /.#Template to edit ideas -->

app/views/ideas/index.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for Idea.new do |f| %>
          <%= f.input :description %>
          <%= f.input :author %>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit 'Submit', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<section class="ideator__block ideator__block--form text-center">
    <div class="ideator__block-row">
        
        <div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <div class="btn-group ideator__btn-group ideator__btn-group--idea">
                        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Add Idea</button>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</section>

<section class="ideator__block ideator__block--form text-center">
    <div class="ideator__block-row">
        
        <div class="container">
            <% if flash[:alert] %>
                <div class="ideator__message ideator__message--big ideator__message--error"><%= flash[:alert] %></div>
            <% end %>
        </div>
    </div>
</section>

<section class="ideator__block ideator__block--intro">
    <div class="ideator__block-row">
        
        <div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <% @ideas.each do |idea| %>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <blockquote>
                                    <p><%= idea.description %></p>
                                    <small><%= idea.author %></small>
                                </blockquote>
                                <div class="btn-group ideator__btn-group ideator__btn-group--action" role="group">
                                    <%= link_to 'Revise', edit_idea_path(idea), class: 'btn btn-sm btn-success' %>
                                    <%= link_to 'Delete', idea_path(idea), class: 'btn btn-sm btn-danger', method: :delete, data: {confirm: "Are you sure?"} %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
        
    </div>
</section>

<section class="ideator__block ideator__block--pagination text-center">
    <div class="ideator__block-row">
        
        <div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <%= will_paginate @ideas %>
                </div>
            </div>
        </div>
        
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Importing web fonts from Google fonts library -->
  <link href="https://fonts.googleapis.com/css?family=Dosis:300,400,600,700|Open+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
  <!-- /.#Importing web fonts from Google fonts library -->
</head>
<body>
  
  <!-- Outer wrapper of the Ideator App -->
  <div id="ideator__wrap" class="ideator__wrap" role="main">
    <!-- Structure imported/included/rendered from _nav.html.erb partial -->
    <%= render 'shared/nav' %>
    <!-- /.#Structure imported/included/rendered from _nav.html.erb partial -->
    
    <!-- Main body section of the Ideator App -->
    <main id="ideator__main" class="ideator__main" role="main">
      <%= yield %>
    </main><!-- /.#Main body section of the Ideator App -->
    
    <!-- Structure imported/included/rendered from _footer.html.erb partial -->
    <%= render 'shared/footer' %>
    <!-- /.#Structure imported/included/rendered from _footer.html.erb partial -->
    
  </div><!-- Outer wrapper of the Ideator App -->
  
</body>
</html>

app/views/shared/_footer.html.erb
<!-- Partial file that contains structure related to footer of the ideator application -->

<footer id="ideator__colphon" class="footer ideator__footer text-center" role="content-info">
    <div class="container">
        <div class="row clearfix">
            <div class="col-xs-12">
                <p>© TECHRISE <%= Date.today.year %> All Rights Reserved</p>    
            </div>
        </div>
    </div>
</footer>

app/views/shared/_nav.html.erb
<!-- Partial file that contains structure related to navigation of the ideator application -->

<!-- Adding bootstrap nav in Ideator App -->
<header id="ideator__masthead" class="ideator__header ideator__masthead">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="row clearfix">
        <div class="col-xs-12">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Ideator', root_path, class: "navbar-brand" %>
          </div>
  
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav" role="menu">
              <li><%= link_to 'All Ideas', root_path %></li>
              <li><%= link_to 'Inspire Me', random_path %></li>
              <li><%= link_to 'About', about_path %></li>
            </ul>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </nav><!-- /.#Adding bootstrap nav in Ideator App -->
</header><!-- /.#Ideator App's header -->

app/views/static_pages/about.html.erb
<section class="ideator__block ideator__block--intro text-center">
    <div class="ideator__block-row">
        
        <div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <h1>About</h1>

                    <h4>Share your ideas with the world and find others.</h4>
                    
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
            </div>
        </div>
        
    </div>
</section>

app/views/static_pages/random.html.erb
<section class="ideator__block ideator__block--form">
    <div class="ideator__block-row">
        
        <div class="container">
            <div class="row clearfix">
                <div class="col-xs-12">
                    <div class="panel panel-default">
                      <div class="panel-body">
                        <blockquote>
                          <p><%= @idea.description %></p>
                          <small>by <%= @idea.author %></small>
                        </blockquote>
                          
                        <br>
                    
                        <div class="btn-group" role="group">
                          <%= link_to 'Delete', idea_path(@idea), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
                          <%= link_to 'Revise', edit_idea_path(@idea), class: 'btn btn-sm btn-success' %>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>